version: '3'

networks:
  app-tier:
    driver: bridge

services:
  hw11-server:
    build: .
    ports: 
      - "3000:3000"
    volumes:  
      - .:/usr/src/app
    networks:
      - app-tier
    depends_on:
      - pgsqldb
  pgsqldb:
    image:  postgres:12
    ports: 
      - "5432:5432"
    networks:
      - app-tier
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
    volumes:
      - './postgres-data:/var/lib/postgressql/data'